pipeline {
    agent none
    stages {
        stage('Maven Build') {
            agent {
                docker {
                    image 'maven:3-jdk-11'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
                stash includes: '**/target/*.jar', name: 'lte-jar'
            }
        }
        stage('Test - Linux') {
            agent {
                docker {
                    image 'adoptopenjdk/openjdk11:alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                unstash 'lte-jar'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/linux/*.xml'
                }
            }
        }
        stage('Test - Windows') {
            agent {
                label 'windows-build'
            }
            steps {
                unstash 'lte-jar'
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/windows/*.xml'
                }
            }
        }
        stage('Build Docker Image') {
            agent {
                label 'windows-build'
            }
            steps {
                sh './jenkins/scripts/build-and-deploy-image.cmd'
            }
        }
    }
}
